"use client";
import { useState } from 'react';
import Card from '../Card';
import type { ContentDoc, ContentIdea } from '../types';
import { safeLink, editorialIdeas, type Draft, type Editorial } from '@/lib/contentPlan';
export default function IdeaBox({ doc, editorial, today, onChange, onOpen }: { doc: ContentDoc; editorial: Editorial | null; today: string; onChange: (d: ContentDoc) => void; onOpen: (d: Draft) => void }) {
 const [filter,setFilter]=useState<'inspiration'|'saved'|'done'>('inspiration');
 const [search,setSearch]=useState(''),[editing,setEditing]=useState<ContentIdea|null>(null),[error,setError]=useState('');
 const ideas=doc.ideas||[];
 const suggestions=editorialIdeas(editorial);
 const normalize=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('fr');
 const match=(text:string)=>normalize(text).includes(normalize(search.trim()));
 const rows=ideas.filter(i=>filter==='done'?i.done:!i.done).filter(i=>match(`${i.text} ${i.note||''} ${i.url||''}`));
 const update=(idea:ContentIdea)=>onChange({...doc,ideas:[...ideas.filter(i=>i.id!==idea.id),idea]});
 const retain=(d:typeof suggestions[number])=>{update({id:crypto.randomUUID(),sourceId:d.id,text:d.title,url:d.source,discussionUrl:d.trend?.url,draft:{...d},note:'',format:d.kind,done:false,created:today,day:today});};
 const save=()=>{if(!editing)return;if(!editing.text.trim()){setError('Ajoute un titre.');return;}let url=editing.url?.trim();if(url&&!/^https?:\/\//i.test(url))url=`https://${url}`;if(url&&!safeLink(url)){setError('Utilise un lien https valide.');return;}update({...editing,text:editing.text.trim(),url});setEditing(null);setError('');setFilter(editing.done?'done':'saved');};
 const link=(url?:string)=>safeLink(url)?<a href={safeLink(url)} target="_blank" rel="noreferrer">{new URL(url!).hostname.replace(/^www\./,'')} ↗</a>:null;
 return <Card title="boîte à idées" span={12} i={0} className="idea-box" aside={<button onClick={()=>{setEditing({id:crypto.randomUUID(),text:'',url:'',note:'',format:'video',done:false,created:today});setError('');}}>+ ajouter une idée</button>}>
  <div className="idea-toolbar"><div className="studio-filters" aria-label="filtrer les idées"><button aria-pressed={filter==='inspiration'} onClick={()=>setFilter('inspiration')}>à explorer</button><button aria-pressed={filter==='saved'} onClick={()=>setFilter('saved')}>retenues · {ideas.filter(i=>!i.done).length}</button><button aria-pressed={filter==='done'} onClick={()=>setFilter('done')}>faites · {ideas.filter(i=>i.done).length}</button></div><input type="search" aria-label="chercher une idée" placeholder="chercher un sujet…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch('')}>effacer la recherche</button>}</div>
  {editing&&<form className="idea-form" onSubmit={e=>{e.preventDefault();save();}}><label>idée<input autoFocus value={editing.text} onChange={e=>setEditing({...editing,text:e.target.value})} placeholder="Le sujet que tu veux creuser"/></label><label>lien direct<input type="text" inputMode="url" value={editing.url||''} onChange={e=>setEditing({...editing,url:e.target.value})} placeholder="https://…"/></label><label>ta note<textarea rows={3} value={editing.note||''} onChange={e=>setEditing({...editing,note:e.target.value})} placeholder="Ce qui t’intéresse, ton angle…"/></label><label>format<select value={editing.format||'video'} onChange={e=>setEditing({...editing,format:e.target.value as 'x'|'video'})}><option value="video">vidéo</option><option value="x">X</option></select></label><div className="content-actions"><button className="content-primary" type="submit">enregistrer</button><button type="button" onClick={()=>{setEditing(null);setError('');}}>annuler</button></div>{error&&<p role="alert" className="hint">{error}</p>}</form>}
  <div className="idea-grid">{filter==='inspiration'?suggestions.filter(d=>match(`${d.title} ${d.source||''}`)).map(d=>{const kept=ideas.some(i=>i.sourceId===d.id);return <article className="idea-item" key={d.id}><div className="idea-meta">{d.kind==='x'?'X':'vidéo'} · {d.day.slice(8)}/{d.day.slice(5,7)}</div><h3>{d.title}</h3><div className="idea-links">{link(d.source)}{safeLink(d.trend?.url)&&<a href={safeLink(d.trend?.url)} target="_blank" rel="noreferrer">discussion ↗</a>}</div><div className="content-actions"><button onClick={()=>onOpen(d)}>{d.kind==='x'?'ouvrir le post':'ouvrir le script'} ↗</button><button className="idea-keep" disabled={kept} onClick={()=>retain(d)}>{kept?'gardée ✓':'+ garder l’idée'}</button></div></article>;}):rows.map(i=><article className="idea-item" key={i.id}><div className="idea-meta">{i.format==='x'?'X':i.format==='video'?'vidéo':'idée'} · {i.created?.slice(0,10)}</div><h3>{i.text}</h3>{i.note&&<p>{i.note}</p>}<div className="idea-links">{link(i.url)}{safeLink(i.discussionUrl)&&<a href={safeLink(i.discussionUrl)} target="_blank" rel="noreferrer">discussion ↗</a>}</div><div className="content-actions">{(i.draft||suggestions.find(d=>d.id===i.sourceId)||doc.drafts?.find(d=>d.id===i.sourceId))&&<button onClick={()=>onOpen((i.draft||suggestions.find(d=>d.id===i.sourceId)||doc.drafts?.find(d=>d.id===i.sourceId))!)}>ouvrir {i.format==='x'?'le post':'le script'} ↗</button>}<button onClick={()=>{setEditing({...i});setError('');}}>modifier</button><button onClick={()=>update({...i,done:!i.done})}>{i.done?'remettre à faire':'marquer faite ✓'}</button></div></article>)}</div>
  {(filter==='inspiration'?suggestions.filter(d=>match(`${d.title} ${d.source||''}`)).length===0:rows.length===0)&&<p className="idea-empty">{search?'Aucune idée ne correspond.':filter==='saved'?'Garde un sujet à explorer ou ajoute ton propre lien.':filter==='done'?'Tes idées réalisées apparaîtront ici.':'Les sujets sourcés du prochain brief apparaîtront ici.'}</p>}
 </Card>;
}
